//! Per-campaign SQLite vault (ADR-CIP one-vault-per-campaign, CIP-158/154/149).
//!
//! Opens/creates a campaign's `campaign.cipdb`, applies migrations, and provides the
//! campaign/session operations the app commands need. All ids are TEXT UUIDs generated by SQLite.

use rusqlite::Connection;
use serde::Serialize;
use std::path::Path;

const MIGRATION_0001: &str = include_str!("migrations/0001_init.sql");

#[derive(Debug, thiserror::Error)]
pub enum VaultError {
    #[error("sqlite error: {0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("vault has no campaign row")]
    NoCampaign,
}
pub type Result<T> = std::result::Result<T, VaultError>;

#[derive(Debug, Serialize)]
pub struct Campaign {
    pub id: String,
    pub name: String,
    pub game_system: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct Session {
    pub id: String,
    pub session_number: f64,
    pub title: Option<String>,
    pub source: String,
    pub recorded_at: String,
    pub status: String,
}

pub struct Vault {
    conn: Connection,
}

impl Vault {
    /// Open (creating if needed) the vault at `db_path`, applying migrations.
    pub fn open(db_path: &Path) -> Result<Self> {
        if let Some(parent) = db_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let conn = Connection::open(db_path)?;
        conn.execute_batch(MIGRATION_0001)?;
        Ok(Self { conn })
    }

    /// Create the vault's single campaign anchor. Fails if one already exists (single-row invariant).
    pub fn init_campaign(&self, name: &str, game_system: Option<&str>) -> Result<Campaign> {
        self.conn.execute(
            "INSERT INTO campaigns (name, game_system) VALUES (?1, ?2)",
            (name, game_system),
        )?;
        self.campaign()
    }

    pub fn campaign(&self) -> Result<Campaign> {
        self.conn
            .query_row(
                "SELECT id, name, game_system FROM campaigns WHERE singleton = 1",
                [],
                |r| Ok(Campaign { id: r.get(0)?, name: r.get(1)?, game_system: r.get(2)? }),
            )
            .map_err(|e| match e {
                rusqlite::Error::QueryReturnedNoRows => VaultError::NoCampaign,
                other => VaultError::Sqlite(other),
            })
    }

    /// Suggest the next whole session number (max whole + 1), for the capture UI (CIP-149).
    pub fn next_session_number(&self) -> Result<f64> {
        let max: Option<f64> = self.conn.query_row(
            "SELECT MAX(session_number) FROM sessions",
            [],
            |r| r.get(0),
        )?;
        Ok(match max {
            Some(m) => (m.floor()) + 1.0,
            None => 1.0,
        })
    }

    /// Create a session row (source = live|upload). recorded_at is caller-supplied (editable).
    pub fn create_session(
        &self,
        session_number: f64,
        title: Option<&str>,
        source: &str,
        recorded_at: &str,
    ) -> Result<Session> {
        let campaign = self.campaign()?;
        self.conn.execute(
            "INSERT INTO sessions (campaign_id, session_number, title, source, recorded_at, status)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            (
                &campaign.id,
                session_number,
                title,
                source,
                recorded_at,
                if source == "live" { "recording" } else { "imported" },
            ),
        )?;
        let id: String = self.conn.query_row(
            "SELECT id FROM sessions WHERE campaign_id = ?1 AND session_number = ?2",
            (&campaign.id, session_number),
            |r| r.get(0),
        )?;
        Ok(Session {
            id,
            session_number,
            title: title.map(str::to_string),
            source: source.to_string(),
            recorded_at: recorded_at.to_string(),
            status: if source == "live" { "recording" } else { "imported" }.to_string(),
        })
    }

    /// Sessions ordered for cataloguing (ascending by number; late/out-of-order uploads slot in).
    pub fn list_sessions(&self) -> Result<Vec<Session>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, session_number, title, source, recorded_at, status
             FROM sessions ORDER BY session_number ASC",
        )?;
        let rows = stmt.query_map([], |r| {
            Ok(Session {
                id: r.get(0)?,
                session_number: r.get(1)?,
                title: r.get(2)?,
                source: r.get(3)?,
                recorded_at: r.get(4)?,
                status: r.get(5)?,
            })
        })?;
        Ok(rows.collect::<std::result::Result<Vec<_>, _>>()?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn mem_vault() -> Vault {
        let conn = Connection::open_in_memory().unwrap();
        conn.execute_batch(MIGRATION_0001).unwrap();
        Vault { conn }
    }

    #[test]
    fn campaign_is_single_row_anchor() {
        let v = mem_vault();
        let c = v.init_campaign("Curse of Strahd", Some("D&D 5e")).unwrap();
        assert!(!c.id.is_empty());
        // second campaign in the same vault must violate the single-row invariant
        assert!(v.init_campaign("Another", None).is_err());
    }

    #[test]
    fn session_numbering_and_ordering() {
        let v = mem_vault();
        v.init_campaign("Test", None).unwrap();
        assert_eq!(v.next_session_number().unwrap(), 1.0);

        v.create_session(1.0, Some("One"), "live", "2026-01-01T19:00:00Z").unwrap();
        v.create_session(2.0, Some("Two"), "live", "2026-01-08T19:00:00Z").unwrap();
        assert_eq!(v.next_session_number().unwrap(), 3.0);

        // a late/out-of-order upload slots between 1 and 2 as 1.5
        v.create_session(1.5, Some("Flashback"), "upload", "2026-01-04T12:00:00Z").unwrap();
        let nums: Vec<f64> = v.list_sessions().unwrap().iter().map(|s| s.session_number).collect();
        assert_eq!(nums, vec![1.0, 1.5, 2.0]);

        // exact duplicate is rejected by the UNIQUE(campaign_id, session_number) constraint
        assert!(v.create_session(1.0, None, "live", "2026-01-01T19:00:00Z").is_err());
    }
}
