-- Add ticket_code column
ALTER TABLE work_items ADD COLUMN ticket_code TEXT UNIQUE;

CREATE INDEX idx_work_items_ticket_code ON work_items (ticket_code) WHERE ticket_code IS NOT NULL;

COMMENT ON COLUMN work_items.ticket_code IS 'Auto-generated ticket code: {PROJECT_KEY}-{SEQUENCE}. Example: CIP-001, SB-042. Generated by trigger on INSERT. Manual override allowed.';

-- Create the auto-generation trigger function
CREATE OR REPLACE FUNCTION generate_ticket_code()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path TO ''
AS $function$
DECLARE
  v_project_key TEXT;
  v_next_seq INTEGER;
  v_code TEXT;
BEGIN
  -- Skip if ticket_code already set (allows manual override and safe backfill)
  IF NEW.ticket_code IS NOT NULL THEN
    RETURN NEW;
  END IF;

  -- Get the project_key
  SELECT project_key INTO v_project_key
  FROM public.projects WHERE id = NEW.project_id;

  -- If no project_key, skip code generation
  IF v_project_key IS NULL THEN
    RETURN NEW;
  END IF;

  -- Advisory lock to prevent concurrent sequence conflicts
  PERFORM pg_advisory_xact_lock(hashtext('ticket_' || v_project_key));

  -- Get the next sequence number for this project_key
  SELECT COALESCE(MAX(
    CASE WHEN ticket_code ~ ('^' || v_project_key || '-[0-9]+$')
    THEN CAST(SPLIT_PART(ticket_code, '-', array_length(string_to_array(ticket_code, '-'), 1)) AS INTEGER)
    ELSE 0 END
  ), 0) + 1 INTO v_next_seq
  FROM public.work_items
  WHERE ticket_code LIKE v_project_key || '-%';

  -- Generate code with zero-padding (3 digits, expands naturally past 999)
  v_code := v_project_key || '-' || LPAD(v_next_seq::TEXT, 3, '0');

  NEW.ticket_code := v_code;
  RETURN NEW;
END;
$function$;

CREATE TRIGGER trg_generate_ticket_code
  BEFORE INSERT ON work_items
  FOR EACH ROW
  EXECUTE FUNCTION generate_ticket_code();;
