
-- SB-383 step 4, now resolvable. Jason: the delegation map IS JARVIS's instruction set.
--
-- JARVIS's prompt already said "Route requests to the appropriate Project PM per the
-- delegation map" — and no such section existed. The prompt cited a document that was not
-- there, one level above SB-383 citing the same missing thing. Exactly the fault SB-397
-- was written to prevent, in the instruction set that governs routing.
--
-- Generated from agent_directs and agent_projects, so it cannot go stale the way a typed
-- list would — the correction SB-402 made to the chain block, applied here from the start.
create or replace function public.jarvis_delegation_map()
returns text
language sql
stable
set search_path to 'public'
as $fn$
  select '## PM DELEGATION MAP (generated — do not edit by hand)' || chr(10) ||
         'Route work to the PM that owns the project key. Never bypass a PM to coordinate ' ||
         'individual project agents.' || chr(10) || chr(10) ||
         string_agg(
           '- **' || d.direct_name || '** — ' ||
           coalesce((select string_agg(distinct pr.project_key, ' / ' order by pr.project_key)
                       from agent_projects ap join projects pr on pr.id = ap.project_id
                      where ap.agent_id = d.direct_id), 'no project registered') ||
           coalesce(' (' || (select a2.meta->>'domain' from agents a2 where a2.id = d.direct_id) || ')', ''),
           chr(10) order by d.direct_name)
  from agent_directs d
  where d.agent_name = 'JARVIS — Master Orchestrator' and d.direct_status = 'active';
$fn$;

comment on function public.jarvis_delegation_map() is
  'SB-383: the PM delegation map JARVIS''s instruction set refers to, derived from agent_directs and agent_projects. Regenerated by trg_regen_delegation_map.';

create or replace function public.regenerate_delegation_map()
returns trigger
language plpgsql
set search_path to 'public'
as $fn$
begin
  update agents
     set system_prompt = regexp_replace(
           system_prompt,
           '## PM DELEGATION MAP \(generated[\s\S]*?(?=\n## |$)',
           replace(public.jarvis_delegation_map(), '\', '\\') || chr(10))
   where name = 'JARVIS — Master Orchestrator'
     and system_prompt like '%## PM DELEGATION MAP (generated%';
  return null;
end;
$fn$;

drop trigger if exists trg_regen_delegation_map on public.agent_projects;
create trigger trg_regen_delegation_map
  after insert or delete on public.agent_projects
  for each statement execute function public.regenerate_delegation_map();
;
